### ISSUE TITLE
global variable?!?

### ISSUE THREAD

**Issue by paolobenve** [e-sites/php-mysql-mysqli-wrapper#5]
using a global variable `$link` exposes to the risk of overwriting/being it overwritten by an identical app variable.

$link should at least be renamed to something weird, e.g. $myyyyyyyLink in order to avoid the issue

**Comment by paolobenve** [comment]
It seems that the issue is only with php7, in php5 the wrapper does what it must do

**Comment by Anton-Korduan** [comment]
I've got the same problem (took me a while to find the global use of "$link") - but I downloadet the wrapper in November ... is this really fixed?

**Comment by sjoerdmaessen** [comment]
This is now fixed, sorry for the late update.
